# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 01:31
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('activity_type', models.CharField(max_length=3)),
                ('learning_obj', models.CharField(max_length=8)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('start_date',),
            },
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('advisor_type', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('coordinator_type', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('school_id', models.CharField(max_length=6)),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField(verbose_name='State/province')),
                ('country', models.TextField()),
            ],
            bases=('auth.group',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('personal_code', models.CharField(max_length=6)),
                ('student_id', models.CharField(max_length=4)),
                ('grad_year', models.IntegerField()),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.School')),
                ('student_advisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.Advisor')),
                ('student_coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.Coordinator')),
            ],
            options={
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='coordinator',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.School'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='advisor_coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.Coordinator'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.School'),
        ),
        migrations.AddField(
            model_name='activity',
            name='entries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Entry'),
        ),
    ]
