# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CommaSeparatedIntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='activity',
            name='learning_obj',
            field=models.CommaSeparatedIntegerField(max_length=8),
        ),
    ]
